import { writeFile } from "node:fs/promises";
import { relative, join } from "node:path";
import { readFileSync } from "node:fs";
import type { LintResult, Diagnostic, Severity } from "../core/types.js";
import pc from "picocolors";
import { printStats, PRIMARY } from "./vibrascope.js";

export type FormatType = "pretty" | "compact" | "plan" | "json";

interface PrintOptions {
  format: FormatType;
  duration: number;
  filesAnalyzed: number;
  fixableErrors?: number;
  fixableWarnings?: number;
  path?: string;
}

export async function printResults(
  results: LintResult[],
  options: PrintOptions,
): Promise<void> {
  switch (options.format) {
    case "compact":
      printCompact(results, options);
      break;
    case "plan":
      await printPlan(results, options);
      break;
    case "json":
      printJson(results, options);
      break;
    case "pretty":
    default:
      printPretty(results, options);
      break;
  }
}

function printPretty(results: LintResult[], options: PrintOptions): void {
  let allDiagnostics = results.flatMap((r) => r.diagnostics);
  const totalErrors = results.reduce((sum, r) => sum + r.errorCount, 0);
  const totalWarnings = results.reduce((sum, r) => sum + r.warningCount, 0);

  if (allDiagnostics.length === 0) {
    printPrettySuccess(options);
    return;
  }

  const byFile = new Map<string, Diagnostic[]>();
  for (const diagnostic of allDiagnostics) {
    const list = byFile.get(diagnostic.file) ?? [];
    list.push(diagnostic);
    byFile.set(diagnostic.file, list);
  }

  console.log(PRIMARY(pc.bold("  Analysis Results")));
  console.log();

  for (const [file, diagnostics] of byFile) {
    const relativePath = rel(file);

    for (const diagnostic of diagnostics) {
      const icon =
        diagnostic.severity === "error"
          ? "✖"
          : diagnostic.severity === "warn"
            ? "⚠"
            : "ℹ";
      const headerColor =
        diagnostic.severity === "error"
          ? pc.red
          : diagnostic.severity === "warn"
            ? pc.yellow
            : PRIMARY;

      console.log(
        `  ${headerColor(relativePath)}:${diagnostic.line}:${diagnostic.column}`,
      );
      console.log(`    ${pc.dim("└─")} ${diagnostic.ruleId}`);

      const messageLines = diagnostic.message.split("\n");
      for (const msgLine of messageLines) {
        console.log(`       ${icon} ${msgLine}`);
      }

      if (diagnostic.suggestions?.length) {
        console.log(
          `       ${pc.green("→")} ${diagnostic.suggestions[0].desc}`,
        );
      }

      if (diagnostic.fix) {
        console.log(`       ${pc.dim("fix available with --fix")}`);
      }

      console.log();
    }
  }

  printStats(
    totalErrors,
    totalWarnings,
    options.filesAnalyzed,
    options.duration,
  );

  const totalFixable =
    (options.fixableErrors || 0) + (options.fixableWarnings || 0);
  if (totalFixable > 0) {
    console.log(
      pc.dim(
        `  Run ${PRIMARY("vibrant --fix")} to auto-fix ${totalFixable} issues`,
      ),
    );
    console.log();
  }
}

function printPrettySuccess(options: PrintOptions): void {
  console.log();
  console.log(pc.green(pc.bold("  ✓ No issues found")));
  console.log(
    pc.dim(
      `  ${options.filesAnalyzed} file${options.filesAnalyzed > 1 ? "s" : ""} · ${options.duration}ms`,
    ),
  );
  console.log();
}

function printCompact(results: LintResult[], options: PrintOptions): void {
  const allDiagnostics = results.flatMap((r) => r.diagnostics);

  if (allDiagnostics.length === 0) {
    console.log();
    console.log(pc.green("  ✓ No issues found"));
    console.log();
    return;
  }

  for (const d of allDiagnostics) {
    const icon =
      d.severity === "error" ? "✖" : d.severity === "warn" ? "⚠" : "ℹ";
    const color =
      d.severity === "error"
        ? pc.red
        : d.severity === "warn"
          ? pc.yellow
          : PRIMARY;
    console.log(
      `${color(icon)} ${rel(d.file)}:${d.line}:${d.column} ${PRIMARY(d.ruleId)} ${d.message.slice(0, 60)}`,
    );
  }

  const totalErrors = results.reduce((sum, r) => sum + r.errorCount, 0);
  const totalWarnings = results.reduce((sum, r) => sum + r.warningCount, 0);
  console.log();
  console.log(
    pc.dim(
      `  ${totalErrors} errors · ${totalWarnings} warnings · ${options.duration}ms`,
    ),
  );
  console.log();
}

async function printPlan(
  results: LintResult[],
  options: PrintOptions,
): Promise<void> {
  const allDiagnostics = results.flatMap((r) => r.diagnostics);
  const totalErrors = results.reduce((sum, r) => sum + r.errorCount, 0);
  const totalWarnings = results.reduce((sum, r) => sum + r.warningCount, 0);

  const lines: string[] = [];

  lines.push(`# 🔍 Vibrant Analysis Report`);
  lines.push(``);
  lines.push(`> Generated by [Vibrant](https://github.com/francogalfre/vibrant) - Vibecode Detector`);
  lines.push(``);

  lines.push(`## 📊 Summary`);
  lines.push(``);
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| 📁 Files Analyzed | ${options.filesAnalyzed} |`);
  lines.push(`| ❌ Errors | ${totalErrors} |`);
  lines.push(`| ⚠️ Warnings | ${totalWarnings} |`);
  lines.push(`| ⏱️ Duration | ${options.duration}ms |`);
  lines.push(``);

  if (allDiagnostics.length === 0) {
    lines.push(`## ✅ Result`);
    lines.push(``);
    lines.push(`No issues found! Your code is clean.`);
    lines.push(``);
  } else {
    lines.push(`## 🔧 Issues to Fix`);
    lines.push(``);
    lines.push(`Below is a detailed list of issues found. Use this report to fix them manually or with AI assistance.`);
    lines.push(``);

    const byFile = new Map<string, Diagnostic[]>();
    for (const d of allDiagnostics) {
      const list = byFile.get(d.file) ?? [];
      list.push(d);
      byFile.set(d.file, list);
    }

    let issueNum = 1;
    for (const [file, diagnostics] of byFile) {
      const relativePath = rel(file);
      
      lines.push(`### 📄 \`${relativePath}\``);
      lines.push(``);

      for (const d of diagnostics) {
        const severityEmoji = d.severity === "error" ? "❌" : d.severity === "warn" ? "⚠️" : "ℹ️";
        const severityLabel = d.severity.toUpperCase();

        lines.push(`#### Issue #${issueNum}: ${severityEmoji} ${severityLabel}`);
        lines.push(``);
        lines.push(`**Rule:** \`${d.ruleId}\``);
        lines.push(``);
        lines.push(`**Location:** Line ${d.line}, Column ${d.column}`);
        lines.push(``);
        lines.push(`**Problem:**`);
        lines.push(``);
        lines.push(`${d.message}`);
        lines.push(``);

        const codeContext = getCodeContext(file, d.line, 3);
        if (codeContext.length > 0) {
          lines.push(`**Code:**`);
          lines.push(``);
          lines.push("```" + getFileExtension(file));
          for (const ctx of codeContext) {
            if (ctx.line === d.line) {
              lines.push(`${ctx.code}  // <-- Issue here`);
            } else {
              lines.push(ctx.code);
            }
          }
          lines.push("```");
          lines.push(``);
        }

        if (d.suggestions?.length) {
          lines.push(`**Suggestion:**`);
          lines.push(``);
          lines.push(`> ${d.suggestions[0].desc}`);
          lines.push(``);
        }

        if (d.fix) {
          lines.push(`**Auto-fix:** Available (run \`vibrant --fix\`)`);
          lines.push(``);
        }

        lines.push(`---`);
        lines.push(``);
        issueNum++;
      }
    }

    lines.push(`## 🤖 AI Fix Prompt`);
    lines.push(``);
    lines.push(`Copy and paste this to an AI assistant to help fix these issues:`);
    lines.push(``);
    lines.push("```");
    lines.push(`Please fix the ${allDiagnostics.length} issues found in this codebase. `);
    lines.push(`Focus on ${totalErrors > 0 ? `the ${totalErrors} errors first` : `the ${totalWarnings} warnings`}.`);
    lines.push(`Each issue includes the file path, line number, and a suggestion.`);
    lines.push("```");
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(``);
  lines.push(`*Report generated in ${options.duration}ms*`);

  const content = lines.join("\n");

  if (options.path) {
    const outputPath = join(process.cwd(), options.path);
    await writeFile(outputPath, content, "utf-8");
    console.log();
    console.log(pc.green(`  ✓ Report saved to ${outputPath}`));
    console.log();
  }
}

function getCodeContext(
  file: string,
  errorLine: number,
  contextLines: number = 3,
): Array<{ line: number; code: string }> {
  try {
    const content = readFileSync(file, "utf-8");
    const lines = content.split("\n");
    const context: Array<{ line: number; code: string }> = [];

    const startLine = Math.max(1, errorLine - contextLines);
    const endLine = Math.min(lines.length, errorLine + contextLines);

    for (let i = startLine; i <= endLine; i++) {
      context.push({ line: i, code: lines[i - 1] || "" });
    }

    return context;
  } catch {
    return [];
  }
}

function getFileExtension(file: string): string {
  const ext = file.split(".").pop()?.toLowerCase();
  switch (ext) {
    case "ts":
    case "tsx":
      return "typescript";
    case "js":
    case "jsx":
      return "javascript";
    case "json":
      return "json";
    case "md":
      return "markdown";
    default:
      return ext || "";
  }
}

function printJson(results: LintResult[], options: PrintOptions): void {
  const output = {
    summary: {
      filesAnalyzed: options.filesAnalyzed,
      errorCount: results.reduce((sum, r) => sum + r.errorCount, 0),
      warningCount: results.reduce((sum, r) => sum + r.warningCount, 0),
      duration: options.duration,
    },
    results: results.map((r) => ({
      file: r.file,
      errors: r.errorCount,
      warnings: r.warningCount,
      issues: r.diagnostics.map((d) => ({
        rule: d.ruleId,
        severity: d.severity,
        line: d.line,
        column: d.column,
        message: d.message,
      })),
    })),
  };

  console.log(JSON.stringify(output, null, 2));
}

function rel(file: string): string {
  try {
    return relative(process.cwd(), file) || file;
  } catch {
    return file;
  }
}
