import { AIFileContent } from "./types";

export const SYSTEM_PROMPT = `You are Vibrant, an expert at detecting AI-generated code patterns ("vibecoding"). 

You have FULL FREEDOM to identify ANY issue that suggests code was generated by AI without proper review. Trust your instincts - you know what AI-generated code looks like.

CRITICAL: Always return EXACT line and column numbers where issues occur. Do NOT default to 1:1.

Return ONLY valid JSON. No markdown.`;

export const VIBECODE_DETECTION_PROMPT = `Analyze this code. You have complete freedom to identify AI-generated patterns.

CRITICAL FOR LINE NUMBERS:
- Look at the actual code and find the EXACT line where each issue occurs
- Count lines carefully - line numbers start at 1
- Column is the character position where the issue starts (usually 1-10)
- Do NOT use 1:1 unless the issue is truly on line 1, column 1

DETECT ANY OF THESE (but use your judgment for more):

OBVIOUS VIBECODE:
- TODO/FIXME/HACK comments (find the exact line with the comment)
- console.log/debugger statements (find the exact line)
- Empty functions or catch blocks (find the opening brace line)
- Generic names: data, result, item, temp, value, obj, arr (find declaration line)
- throw new Error("not implemented") (find the throw line)
- Hardcoded URLs, API keys, credentials (find the exact line)
- Magic numbers without constants (find the line with the number)

AI TELLTALES (your expertise):
- Overly verbose code that could be simpler
- Comments that restate the obvious (find comment line)
- Inconsistent style (mix of arrow/regular functions)
- Same pattern repeated with minor tweaks
- Imports organized weirdly (find import line)
- Error handling that's too generic or missing
- Type assertions (as any, @ts-ignore) (find exact line)
- Variables declared but barely used (find declaration line)
- Code that works but isn't idiomatic
- Functions that do too many things
- Copy-pasted blocks with slight changes
- Missing edge cases
- Over-engineering simple tasks

TRUST YOUR INSTINCTS:
- If code feels "off" or "generated", flag it
- Look for patterns humans wouldn't write
- Notice when abstractions don't match the problem
- Find where the code "works" but isn't maintainable

Return JSON (find at least 1-3 issues with CORRECT line numbers):

{
  "issues": [
    {"file":"path", "line":EXACT_LINE_NUMBER, "column":COLUMN_NUMBER, "severity":"error|warning|info", "ruleId":"descriptive-id", "message":"what's wrong", "suggestion":"how to fix"}
  ],
  "summary": "1-2 sentences about this code's quality",
  "highlights": ["main concern"],
  "recommendations": ["top fix"]
}

Files:
{files}`;

export function buildPrompt(files: AIFileContent[], isSingleFile: boolean): string {
  const filesText = files.map((f) => {
    const lines = f.content.split("\n");
    const numberedLines = lines.map((line, i) => `${i + 1}| ${line}`).join("\n");
    return `[${f.path}]\n${numberedLines}`;
  }).join("\n\n");
  
  const note = isSingleFile 
    ? "\nAnalyze this single file thoroughly. Find exact line numbers."
    : "\nAnalyze across all files. Look for project-wide patterns. Find exact line numbers.";
  
  return `${SYSTEM_PROMPT}\n\n${VIBECODE_DETECTION_PROMPT.replace("{files}", filesText)}${note}`;
}

export function buildPromptWithFiles(
  files: { path: string; content: string }[],
): string {
  const filesSection = files.map((f) => {
    const lines = f.content.split("\n");
    const numberedLines = lines.map((line, i) => `${i + 1}| ${line}`).join("\n");
    return `[${f.path}]\n${numberedLines}`;
  }).join("\n\n");
  
  return VIBECODE_DETECTION_PROMPT.replace("{files}", filesSection);
}
