import { AIFileContent } from "./types";

export const SYSTEM_PROMPT = `You are Vibrant, an expert at detecting AI-generated code patterns ("vibecoding"). 

You have FULL FREEDOM to identify ANY issue that suggests code was generated by AI without proper review. Trust your instincts - you know what AI-generated code looks like.

Return ONLY valid JSON. No markdown.`;

export const VIBECODE_DETECTION_PROMPT = `Analyze this code. You have complete freedom to identify AI-generated patterns.

DETECT ANY OF THESE (but use your judgment for more):

OBVIOUS VIBECODE:
- TODO/FIXME/HACK comments
- console.log/debugger statements
- Empty functions or catch blocks
- Generic names: data, result, item, temp, value, obj, arr
- throw new Error("not implemented")
- Hardcoded URLs, API keys, credentials
- Magic numbers without constants

AI TELLTALES (your expertise):
- Overly verbose code that could be simpler
- Comments that restate the obvious
- Inconsistent style (mix of arrow/regular functions)
- Same pattern repeated with minor tweaks
- Imports organized weirdly
- Error handling that's too generic or missing
- Type assertions (as any, @ts-ignore)
- Variables declared but barely used
- Code that works but isn't idiomatic
- Functions that do too many things
- Copy-pasted blocks with slight changes
- Missing edge cases
- Over-engineering simple tasks

TRUST YOUR INSTINCTS:
- If code feels "off" or "generated", flag it
- Look for patterns humans wouldn't write
- Notice when abstractions don't match the problem
- Find where the code "works" but isn't maintainable

Return JSON (find at least 1-3 issues, even minor ones):

{
  "issues": [
    {"file":"path", "line":1, "column":1, "severity":"error|warning|info", "ruleId":"descriptive-id", "message":"what's wrong", "suggestion":"how to fix"}
  ],
  "summary": "1-2 sentences about this code's quality",
  "highlights": ["main concern"],
  "recommendations": ["top fix"]
}

Files:
{files}`;

export function buildPrompt(files: AIFileContent[], isSingleFile: boolean): string {
  const filesText = files.map((f) => `[${f.path}]\n${f.content}`).join("\n\n");
  const note = isSingleFile 
    ? "\nAnalyze this single file thoroughly."
    : "\nAnalyze across all files. Look for project-wide patterns.";
  
  return `${SYSTEM_PROMPT}\n\n${VIBECODE_DETECTION_PROMPT.replace("{files}", filesText)}${note}`;
}

export function buildPromptWithFiles(
  files: { path: string; content: string }[],
): string {
  const filesSection = files
    .map((f) => `[${f.path}]\n${f.content}`)
    .join("\n\n");
  return VIBECODE_DETECTION_PROMPT.replace("{files}", filesSection);
}
