#!/usr/bin/env bun
/**
 * Pre-commit hook for Vibrant
 * Analyzes staged files before committing
 * 
 * Installation:
 *   bun run cli -- init --hook
 * 
 * Or manually add to .git/hooks/pre-commit:
 *   #!/bin/sh
 *   bun run /path/to/vibrant-hook.ts
 */

import { execSync } from "child_process";
import { existsSync } from "fs";
import { join } from "path";
import { c, theme } from "../ui/theme.js";
import * as logger from "../ui/logger.js";

const cwd = process.cwd();
const hookPath = join(cwd, ".git", "hooks", "pre-commit");

/**
 * Get list of staged files
 */
function getStagedFiles(): string[] {
  try {
    const output = execSync("git diff --cached --name-only --diff-filter=ACM", {
      encoding: "utf-8",
      cwd,
    });
    return output
      .trim()
      .split("\n")
      .filter((f) => f.match(/\.(ts|tsx|js|jsx)$/));
  } catch {
    return [];
  }
}

/**
 * Install pre-commit hook
 */
export function installHook(): void {
  if (!existsSync(join(cwd, ".git"))) {
    logger.error("Not a git repository");
    process.exit(1);
  }

  const hookContent = `#!/bin/sh
# Vibrant pre-commit hook
# Auto-generated by \`vibrant init --hook\`

echo "Running Vibrant on staged files..."
staged_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\\.(ts|tsx|js|jsx)$' || true)

if [ -n "$staged_files" ]; then
  bun run vibrant $staged_files
  if [ $? -ne 0 ]; then
    echo "❌ Commit aborted: Vibrant found issues"
    exit 1
  fi
fi

echo "✅ All checks passed!"
`;

  try {
    const fs = require("fs");
    fs.writeFileSync(hookPath, hookContent, { mode: 0o755 });
    logger.success("✅ Pre-commit hook installed successfully!");
    logger.info(`   Hook location: ${hookPath}`);
    logger.info("   The hook will run Vibrant on staged files before each commit.");
  } catch (error) {
    logger.error(`Failed to install hook: ${error}`);
    process.exit(1);
  }
}

/**
 * Uninstall pre-commit hook
 */
export function uninstallHook(): void {
  if (!existsSync(hookPath)) {
    logger.warn("No pre-commit hook found");
    return;
  }

  try {
    const fs = require("fs");
    const content = fs.readFileSync(hookPath, "utf-8");
    
    if (!content.includes("Vibrant")) {
      logger.warn("Pre-commit hook exists but wasn't created by Vibrant");
      logger.info("   Manual removal required");
      return;
    }

    fs.unlinkSync(hookPath);
    logger.success("✅ Pre-commit hook removed successfully!");
  } catch (error) {
    logger.error(`Failed to uninstall hook: ${error}`);
    process.exit(1);
  }
}

/**
 * Run pre-commit check
 */
export async function runPreCommit(): Promise<void> {
  const stagedFiles = getStagedFiles();

  if (stagedFiles.length === 0) {
    logger.info("No staged TypeScript/JavaScript files to check");
    return;
  }

  logger.info(c.cyan(`Checking ${stagedFiles.length} staged files...\n`));

  // Run vibrant on staged files
  const { runLinter } = await import("../commands/lint.js");
  
  try {
    await runLinter({
      path: stagedFiles,
      ai: false,
      format: "compact",
    });
    
    logger.success("\n✅ All checks passed!");
  } catch {
    logger.error("\n❌ Commit aborted: Vibrant found issues");
    logger.info("   Fix the issues or use --no-verify to skip checks");
    process.exit(1);
  }
}

// Run if executed directly
if (import.meta.main) {
  const args = process.argv.slice(2);
  
  if (args.includes("--install")) {
    installHook();
  } else if (args.includes("--uninstall")) {
    uninstallHook();
  } else {
    runPreCommit();
  }
}